
export const userConstants = {

    USER_CHECKACC_REQUEST: 'USER_CHECKACC_REQUEST',
    USER_CHECKACC_SUCCESS: 'USER_CHECKACC_SUCCESS',
    USER_CHECKACC_FAIL: 'USER_CHECKACC_FAIL',
    USER_CHECKACC_RESET: 'USER_CHECKACC_RESET',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',
    USER_DETAILS_RESET: 'USER_DETAILS_RESET',

    USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
    USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET',

    USER_LIST_REQUEST: 'USER_LIST_REQUEST',
    USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
    USER_LIST_FAIL: 'USER_LIST_FAIL',
    USER_LIST_RESET: 'USER_LIST_RESET',

    USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_DELETE_FAIL: 'USER_DELETE_FAIL',

    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAIL: 'USER_UPDATE_FAIL',
    USER_UPDATE_RESET: 'USER_UPDATE_RESET',
}


export const staffConstants = {
    STAFF_ADD_REQUEST: 'STAFF_ADD_REQUEST',
    STAFF_ADD_SUCCESS: 'STAFF_ADD_SUCCESS',
    STAFF_ADD_FAIL: 'STAFF_ADD_FAIL',

    STAFF_LIST_REQUEST: 'STAFF_LIST_REQUEST',
    STAFF_LIST_SUCCESS: 'STAFF_LIST_SUCCESS',
    STAFF_LIST_FAIL: 'STAFF_LIST_FAIL',
    STAFF_LIST_RESET: 'STAFF_LIST_RESET',
}


export const dishConstants = {
    DISH_ADD_REQUEST: 'DISH_ADD_REQUEST',
    DISH_ADD_SUCCESS: 'DISH_ADD_SUCCESS',
    DISH_ADD_FAIL: 'DISH_ADD_FAIL',

    DISH_LIST_REQUEST: 'DISH_LIST_REQUEST',
    DISH_LIST_SUCCESS: 'DISH_LIST_SUCCESS',
    DISH_LIST_FAIL: 'DISH_LIST_FAIL',
    DISH_LIST_RESET: 'DISH_LIST_RESET',

    DISH_EDIT_REQUEST: 'DISH_EDIT_REQUEST',
    DISH_EDIT_SUCCESS: 'DISH_EDIT_SUCCESS',
    DISH_EDIT_FAIL: 'DISH_EDIT_FAIL',
    DISH_EDIT_RESET: 'DISH_EDIT_RESET',

    DISH_CHANGE_STATUS_REQUEST: 'DISH_CHANGE_STATUS_REQUEST',
    DISH_CHANGE_STATUS_SUCCESS: 'DISH_CHANGE_STATUS_SUCCESS',
    DISH_CHANGE_STATUS_FAIL: 'DISH_CHANGE_STATUS_FAIL',

    DISH_GET_BY_ID_REQUEST: 'DISH_GET_BY_ID_REQUEST',
    DISH_GET_BY_ID_SUCCESS: 'DISH_GET_BY_ID_SUCCESS',
    DISH_GET_BY_ID_FAIL: 'DISH_GET_BY_ID_FAIL',
    DISH_GET_BY_ID_RESET: 'DISH_GET_BY_ID_RESET'
}



export const categoryConstants = {
    CATEGORY_ADD_REQUEST: 'CATEGORY_ADD_REQUEST',
    CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
    CATEGORY_ADD_FAIL: 'CATEGORY_ADD_FAIL',
    CATEGORY_ADD_RESET: 'CATEGORY_ADD_RESET',

    CATEGORY_EDIT_REQUEST: 'CATEGORY_EDIT_REQUEST',
    CATEGORY_EDIT_SUCCESS: 'CATEGORY_EDIT_SUCCESS',
    CATEGORY_EDIT_FAIL: 'CATEGORY_EDIT_FAIL',
    CATEGORY_EDIT_RESET: 'CATEGORY_EDIT_RESET',

    CATEGORY_LIST_REQUEST: 'CATEGORY_LIST_REQUEST',
    CATEGORY_LIST_SUCCESS: 'CATEGORY_LIST_SUCCESS',
    CATEGORY_LIST_FAIL: 'CATEGORY_LIST_FAIL',
    CATEGORY_LIST_RESET: 'CATEGORY_LIST_RESET',

    CATEGORY_CHANGE_STATUS_REQUEST: 'CATEGORY_CHANGE_STATUS_REQUEST',
    CATEGORY_CHANGE_STATUS_SUCCESS: 'CATEGORY_CHANGE_STATUS_SUCCESS',
    CATEGORY_CHANGE_STATUS_FAIL: 'CATEGORY_CHANGE_STATUS_FAIL',
    CATEGORY_CHANGE_STATUS_RESET: 'CATEGORY_CHANGE_STATUS_RESET',
}


export const subCategoryConstatnts = {
    SUB_CATEGORY_ADD_REQUEST: 'SUB_CATEGORY_ADD_REQUEST',
    SUB_CATEGORY_ADD_SUCCESS: 'SUB_CATEGORY_ADD_SUCCESS',
    SUB_CATEGORY_ADD_FAIL: 'SUB_CATEGORY_ADD_FAIL',
    SUB_CATEGORY_ADD_RESET: 'SUB_CATEGORY_ADD_RESET',

    SUB_CATEGORY_EDIT_REQUEST: 'SUB_CATEGORY_EDIT_REQUEST',
    SUB_CATEGORY_EDIT_SUCCESS: 'SUB_CATEGORY_EDIT_SUCCESS',
    SUB_CATEGORY_EDIT_FAIL: 'SUB_CATEGORY_EDIT_FAIL',
    SUB_CATEGORY_EDIT_RESET: 'SUB_CATEGORY_EDIT_RESET',

    SUB_CATEGORY_LIST_REQUEST: 'SUB_CATEGORY_LIST_REQUEST',
    SUB_CATEGORY_LIST_SUCCESS: 'SUB_CATEGORY_LIST_SUCCESS',
    SUB_CATEGORY_LIST_FAIL: 'SUB_CATEGORY_LIST_FAIL',
    SUB_CATEGORY_LIST_RESET: 'SUB_CATEGORY_LIST_RESET',

    SUB_CATEGORY_CHANGE_STATUS_REQUEST: 'SUB_CATEGORY_CHANGE_STATUS_REQUEST',
    SUB_CATEGORY_CHANGE_STATUS_SUCCESS: 'SUB_CATEGORY_CHANGE_STATUS_SUCCESS',
    SUB_CATEGORY_CHANGE_STATUS_FAIL: 'SUB_CATEGORY_CHANGE_STATUS_FAIL',
    SUB_CATEGORY_CHANGE_STATUS_RESET: 'SUB_CATEGORY_CHANGE_STATUS_RESET',
}


export const menuConstants = {
    MENU_ADD_REQUEST: 'MENU_ADD_REQUEST',
    MENU_ADD_SUCCESS: 'MENU_ADD_SUCCESS',
    MENU_ADD_FAIL: 'MENU_ADD_FAIL',
    MENU_ADD_RESET: 'MENU_ADD_RESET',

    MENU_EDIT_REQUEST: 'MENU_EDIT_REQUEST',
    MENU_EDIT_SUCCESS: 'MENU_EDIT_SUCCESS',
    MENU_EDIT_FAIL: 'MENU_EDIT_FAIL',
    MENU_EDIT_RESET: 'MENU_EDIT_RESET',

    MENU_LIST_REQUEST: 'MENU_LIST_REQUEST',
    MENU_LIST_SUCCESS: 'MENU_LIST_SUCCESS',
    MENU_LIST_FAIL: 'MENU_LIST_FAIL',
    MENU_LIST_RESET: 'MENU_LIST_RESET',

    MENU_GET_BY_ID_REQUEST: 'MENU_GET_BY_ID_REQUEST',
    MENU_GET_BY_ID_SUCCESS: 'MENU_GET_BY_ID_SUCCESS',
    MENU_GET_BY_ID_FAIL: 'MENU_GET_BY_ID_FAIL',
    MENU_GET_BY_ID_RESET: 'MENU_GET_BY_ID_RESET',

    MENU_CHANGE_STATUS_REQUEST: 'MENU_CHANGE_STATUS_REQUEST',
    MENU_CHANGE_STATUS_SUCCESS: 'MENU_CHANGE_STATUS_SUCCESS',
    MENU_CHANGE_STATUS_FAIL: 'MENU_CHANGE_STATUS_FAIL',
    MENU_CHANGE_STATUS_RESET: 'MENU_CHANGE_STATUS_RESET',
}

export const blogConstants = {
    BLOG_ADD_REQUEST: 'MENU_ADD_REQUEST',
    BLOG_ADD_SUCCESS: 'MENU_ADD_SUCCESS',
    BLOG_ADD_FAIL: 'MENU_ADD_FAIL',
    BLOG_ADD_RESET: 'MENU_ADD_RESET',

    BLOG_LIST_REQUEST: 'BLOG_LIST_REQUEST',
    BLOG_LIST_SUCCESS: 'BLOG_LIST_SUCCESS',
    BLOG_LIST_FAIL: 'BLOG_LIST_FAIL',
    BLOG_LIST_RESET: 'BLOG_LIST_RESET',

    BLOG_DELETE_REQUEST: 'BLOG_DELETE_REQUEST',
    BLOG_DELETE_SUCCESS: 'BLOG_DELETE_SUCCESS',
    BLOG_DELETE_FAIL: 'BLOG_DELETE_FAIL',
    BLOG_DELETE_RESET: 'BLOG_DELETE_RESET',

    BLOG_CHANGE_STATUS_REQUEST: 'BLOG_CHANGE_STATUS_REQUEST',
    BLOG_CHANGE_STATUS_SUCCESS: 'BLOG_CHANGE_STATUS_SUCCESS',
    BLOG_CHANGE_STATUS_FAIL: 'BLOG_CHANGE_STATUS_FAIL',
    BLOG_CHANGE_STATUS_RESET: 'BLOG_CHANGE_STATUS_RESET',

    BLOG_EDIT_REQUEST: 'BLOG_EDIT_REQUEST',
    BLOG_EDIT_SUCCESS: 'BLOG_EDIT_SUCCESS',
    BLOG_EDIT_FAIL: 'BLOG_EDIT_FAIL',
    BLOG_EDIT_RESET: 'BLOG_EDIT_RESET',


    BLOG_DETAIL_REQUEST: 'BLOG_DETAIL_REQUEST',
    BLOG_DETAIL_SUCCESS: 'BLOG_DETAIL_SUCCESS',
    BLOG_DETAIL_FAIL: 'BLOG_DETAIL_FAIL',
    BLOG_DETAIL_RESET: 'BLOG_DETAIL_RESET',
}

export const tableConstants = {
    TABLE_ADD_REQUEST: 'TABLE_ADD_REQUEST',
    TABLE_ADD_SUCCESS: 'TABLE_ADD_SUCCESS',
    TABLE_ADD_FAIL: 'TABLE_ADD_FAIL',
    TABLE_ADD_RESET: 'TABLE_ADD_RESET',

    TABLE_LIST_REQUEST: 'TABLE_LIST_REQUEST',
    TABLE_LIST_SUCCESS: 'TABLE_LIST_SUCCESS',
    TABLE_LIST_FAIL: 'TABLE_LIST_FAIL',
    TABLE_LIST_RESET: 'TABLE_LIST_RESET',

    TABLE_EDIT_REQUEST: 'TABLE_EDIT_REQUEST',
    TABLE_EDIT_SUCCESS: 'TABLE_EDIT_SUCCESS',
    TABLE_EDIT_FAIL: 'TABLE_EDIT_FAIL',
    TABLE_EDIT_RESET: 'TABLE_EDIT_RESET',

    TABLE_CHANGE_STATUS_REQUEST: 'TABLE_CHANGE_STATUS_REQUEST',
    TABLE_CHANGE_STATUS_SUCCESS: 'TABLE_CHANGE_STATUS_SUCCESS',
    TABLE_CHANGE_STATUS_FAIL: 'TABLE_CHANGE_STATUS_FAIL',
    TABLE_CHANGE_STATUS_RESET: 'TABLE_CHANGE_STATUS_RESET',

    TABLE_GET_BY_ID_REQUEST: 'TABLE_GET_BY_ID_REQUEST',
    TABLE_GET_BY_ID_SUCCESS: 'TABLE_GET_BY_ID_SUCCESS',
    TABLE_GET_BY_ID_FAIL: 'TABLE_GET_BY_ID_FAIL',
    TABLE_GET_BY_ID_RESET: 'TABLE_GET_BY_ID_RESET',
}


export const feedbackConstants = {
    FB_LIST_REQUEST: 'FB_LIST_REQUEST',
    FB_LIST_SUCCESS: 'FB_LIST_SUCCESS',
    FB_LIST_FAIL: 'FB_LIST_FAIL',
    FB_LIST_RESET: 'FB_LIST_RESET',

    FB_DELETE_REQUEST: 'FB_DELETE_REQUEST',
    FB_DELETE_SUCCESS: 'FB_DELETE_SUCCESS',
    FB_DELETE_FAIL: 'FB_DELETE_FAIL',
    FB_DELETE_RESET: 'FB_DELETE_RESET',

    FB_DETAIL_REQUEST: 'FB_DETAIL_REQUEST',
    FB_DETAIL_SUCCESS: 'FB_DETAIL_SUCCESS',
    FB_DETAIL_FAIL: 'FB_DETAIL_FAIL',
    FB_DETAIL_RESET: 'FB_DETAIL_RESET',
}

export const orderConstants = {
    ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
    ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',
    ORDER_LIST_FAIL: 'ORDER_LIST_FAIL',
    ORDER_LIST_RESET: 'ORDER_LIST_RESET',

    ORDER_GET_BY_ID_REQUEST: 'ORDER_GET_BY_ID_REQUEST',
    ORDER_GET_BY_ID_SUCCESS: 'ORDER_GET_BY_ID_SUCCESS',
    ORDER_GET_BY_ID_FAIL: 'ORDER_GET_BY_ID_FAIL',
    ORDER_GET_BY_ID_RESET: 'ORDER_GET_BY_ID_RESET',

    ORDER_ADD_REQUEST: 'ORDER_ADD_REQUEST',
    ORDER_ADD_SUCCESS: 'ORDER_ADD_SUCCESS',
    ORDER_ADD_FAIL: 'ORDER_ADD_FAIL',
    ORDER_ADD_RESET: 'ORDER_ADD_RESET',

    ORDER_CHANGE_STATUS_REQUEST: 'ORDER_CHANGE_STATUS_REQUEST',
    ORDER_CHANGE_STATUS_SUCCESS: 'ORDER_CHANGE_STATUS_SUCCESS',
    ORDER_CHANGE_STATUS_FAIL: 'ORDER_CHANGE_STATUS_FAIL',
    ORDER_CHANGE_STATUS_RESET: 'ORDER_CHANGE_STATUS_RESET',
}

export const bookingTableConstants = {
    BOOKING_TABLE_LIST_REQUEST: 'BOOKING_TABLE_LIST_REQUEST',
    BOOKING_TABLE_LIST_SUCCESS: 'BOOKING_TABLE_LIST_SUCCESS',
    BOOKING_TABLE_LIST_FAIL: 'BOOKING_TABLE_LIST_FAIL',
    BOOKING_TABLE_LIST_RESET: 'BOOKING_TABLE_LIST_RESET',

    BOOKING_TABLE_ADD_REQUEST: 'BOOKING_TABLE_ADD_REQUEST',
    BOOKING_TABLE_ADD_SUCCESS: 'BOOKING_TABLE_ADD_SUCCESS',
    BOOKING_TABLE_ADD_FAIL: 'BOOKING_TABLE_ADD_FAIL',
    BOOKING_TABLE_ADD_RESET: 'BOOKING_TABLE_ADD_RESET',

    BOOKING_TABLE_DETAIL_REQUEST: 'BOOKING_TABLE_DETAIL_REQUEST',
    BOOKING_TABLE_DETAIL_SUCCESS: 'BOOKING_TABLE_DETAIL_SUCCESS',
    BOOKING_TABLE_DETAIL_FAIL: 'BOOKING_TABLE_DETAIL_FAIL',
    BOOKING_TABLE_DETAIL_RESET: 'BOOKING_TABLE_DETAIL_RESET',

    BOOKING_TABLE_CHANGE_STATUS_REQUEST: 'BOOKING_TABLE_CHANGE_STATUS_REQUEST',
    BOOKING_TABLE_CHANGE_STATUS_SUCCESS: 'BOOKING_TABLE_CHANGE_STATUS_SUCCESS',
    BOOKING_TABLE_CHANGE_STATUS_FAIL: 'BOOKING_TABLE_CHANGE_STATUS_FAIL',
    BOOKING_TABLE_CHANGE_STATUS_RESET: 'BOOKING_TABLE_CHANGE_STATUS_RESET',
}