
export const userConstants = {

    USER_CHECKACC_REQUEST: 'USER_CHECKACC_REQUEST',
    USER_CHECKACC_SUCCESS: 'USER_CHECKACC_SUCCESS',
    USER_CHECKACC_FAIL: 'USER_CHECKACC_FAIL',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',
    USER_DETAILS_RESET: 'USER_DETAILS_RESET',

    USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
    USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET',

    USER_LIST_REQUEST: 'USER_LIST_REQUEST',
    USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
    USER_LIST_FAIL: 'USER_LIST_FAIL',
    USER_LIST_RESET: 'USER_LIST_RESET',

    USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_DELETE_FAIL: 'USER_DELETE_FAIL',

    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAIL: 'USER_UPDATE_FAIL',
    USER_UPDATE_RESET: 'USER_UPDATE_RESET',
}


export const staffConstants = {
    STAFF_ADD_REQUEST: 'STAFF_ADD_REQUEST',
    STAFF_ADD_SUCCESS: 'STAFF_ADD_SUCCESS',
    STAFF_ADD_FAIL: 'STAFF_ADD_FAIL',

    STAFF_LIST_REQUEST: 'STAFF_LIST_REQUEST',
    STAFF_LIST_SUCCESS: 'STAFF_LIST_SUCCESS',
    STAFF_LIST_FAIL: 'STAFF_LIST_FAIL',
    STAFF_LIST_RESET: 'STAFF_LIST_RESET',
}


export const dishConstants = {
    DISH_ADD_REQUEST: 'DISH_ADD_REQUEST',
    DISH_ADD_SUCCESS: 'DISH_ADD_SUCCESS',
    DISH_ADD_FAIL: 'DISH_ADD_FAIL',

    DISH_LIST_REQUEST: 'DISH_LIST_REQUEST',
    DISH_LIST_SUCCESS: 'DISH_LIST_SUCCESS',
    DISH_LIST_FAIL: 'DISH_LIST_FAIL',
    DISH_LIST_RESET: 'DISH_LIST_RESET',
}



export const categoryConstants = {
    CATEGORY_ADD_REQUEST: 'CATEGORY_ADD_REQUEST',
    CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
    CATEGORY_ADD_FAIL: 'CATEGORY_ADD_FAIL',
    CATEGORY_ADD_RESET: 'CATEGORY_ADD_RESET',

    CATEGORY_LIST_REQUEST: 'CATEGORY_LIST_REQUEST',
    CATEGORY_LIST_SUCCESS: 'CATEGORY_LIST_SUCCESS',
    CATEGORY_LIST_FAIL: 'CATEGORY_LIST_FAIL',
    CATEGORY_LIST_RESET: 'CATEGORY_LIST_RESET',
}

